### ISSUE TITLE
Suggestion: react-native-firestack

### ISSUE THREAD

**Issue by neosekar** [DimitriMikadze/firebase-react-native-redux-starter#1]
Hi, This is a cool starter. I really looked some kind of starter like this for firebase. This is very useful. In my suggestion for use firebase there is a package called react-native-firestack which has firebase native and javascript support. https://github.com/fullstackreact/react-native-firestack

**Comment by DimiMikadze** [comment]
Hey neosekar, thank you for your suggestion, i'll definitely check ! :)
