### ISSUE TITLE
Error immediately after project start

### ISSUE THREAD

**Issue by gHashTag** [DimitriMikadze/firebase-react-native-redux-starter#11]
Why?
SyntaxError /Users/dmitriyvasilev/firebase-react-native-redux-starter/src/Router.js: Unexpected token, expected
![simulator screen shot 24 2017 20 25 27](https://user-images.githubusercontent.com/6774813/29679423-625ed56a-890a-11e7-840f-29f6522ab0b9.png)

**Comment by DimiMikadze** [comment]
@gHashTag i think you forgot to run `npm install` or didn't created firebase app and configured it: https://github.com/DimitriMikadze/firebase-react-native-redux-starter#user-content-firebase

**Comment by gHashTag** [comment]
@DimitriMikadze and now after `rm -rf node_modules && npm install`
![simulator screen shot 24 2017 21 01 04](https://user-images.githubusercontent.com/6774813/29681154-9bbaea92-890f-11e7-88aa-9839f8d6daea.png)

**Comment by DimiMikadze** [comment]
@gHashTag can't help with info like that, because i can't reproduce same error on my machine.
I think it's not app specific error, can you run other react native projects on your machine?

**Comment by gHashTag** [comment]
@DimitriMikadze Others are working. For example, this is my project with add profile user photo(Blob) in Firebase : 
https://gitlab.com/gHashTag/FirebaseApp/tree/auth/

**Comment by DimiMikadze** [comment]
@gHashTag did you managed to resolve your issue?

**Comment by gHashTag** [comment]
@DimitriMikadze No( I look forward to hearing from you

**Comment by amit-gueta** [comment]
@gHashTag Try to change the version of "react-native-router-flux" to "3.37.0" instead of "^3.37.0"..

**Comment by alialsaeedi19** [comment]
exactly same error here :(

**Comment by clickglue** [comment]
Had the exact same error but changing flux version worked for me.
