### ISSUE TITLE
native-base dependency

### ISSUE THREAD

**Issue by ajostergaard** [DimitriMikadze/firebase-react-native-redux-starter#2]
Looks like native-base should be added to package.json - doesn't compile otherwise.

**Comment by DimiMikadze** [comment]
I tested native base on this repo, but it had some bugs and i removed it from project.

can you tell me when exactly it's not compiling ?

**Comment by ajostergaard** [comment]
We're in luck - my terminal still had the errors:

> 	CpResource firebase-react-native-redux-starter/node_modules/native-base/Fonts/Arial.ttf build/Build/Products/Debug-iphonesimulator/rnauth.app/Arial.ttf
	CpResource firebase-react-native-redux-starter/node_modules/native-base/Fonts/Andale\ Mono.ttf build/Build/Products/Debug-iphonesimulator/rnauth.app/Andale\ Mono.ttf
	CpResource firebase-react-native-redux-starter/node_modules/native-base/Fonts/Courier\ New.ttf build/Build/Products/Debug-iphonesimulator/rnauth.app/Courier\ New.ttf
	CpResource firebase-react-native-redux-starter/node_modules/native-base/Fonts/Arial\ Black.ttf build/Build/Products/Debug-iphonesimulator/rnauth.app/Arial\ Black.ttf
	CpResource firebase-react-native-redux-starter/node_modules/native-base/Fonts/FontAwesome.ttf build/Build/Products/Debug-iphonesimulator/rnauth.app/FontAwesome.ttf
	CpResource firebase-react-native-redux-starter/node_modules/native-base/Fonts/EvilIcons.ttf build/Build/Products/Debug-iphonesimulator/rnauth.app/EvilIcons.ttf
	CpResource firebase-react-native-redux-starter/node_modules/native-base/Fonts/Comic\ Sans\ MS.ttf build/Build/Products/Debug-iphonesimulator/rnauth.app/Comic\ Sans\ MS.ttf
	CpResource firebase-react-native-redux-starter/node_modules/native-base/Fonts/Entypo.ttf build/Build/Products/Debug-iphonesimulator/rnauth.app/Entypo.ttf
(8 failures)

**Comment by DimiMikadze** [comment]
Just fixed the issue and pushed changes to Github. 
native-base was linked with project, you'll need to run 'rnpm unlink-nativebase' from project directory.

Tell me if it will fix your issue

**Comment by ajostergaard** [comment]
Sorted. :)
