### ISSUE TITLE
Concerned about dependency

### ISSUE THREAD

**Issue by ajostergaard** [DimitriMikadze/firebase-react-native-redux-starter#4]
Looking at the state of https://github.com/aksonov/react-native-router-flux/issues with serious issues open since early 2016 I'm concerned about relying on this repo as it depends on that one. Any plans to switch to an alternative? Perhaps even a 100% native one, should one exist?

**Comment by DimiMikadze** [comment]
hey ajostergaard, sorry for very late answer. 

do you know any better alternative?

**Comment by ajostergaard** [comment]
This is not late! :) Unfortunately no, I do not know any alternatives. I'm still very new to React, React Native and even client side coding.

Anyway, I have settled on your starter kit for my first app and so far it's going well. Thank you!!!
