### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by JohnHour89** [DimitriMikadze/firebase-react-native-redux-starter#7]
Hi Mr. DimitriMikadze,

I was able to run the application successfully but when I want to Sign up for the new account it returned me "Authentication failed" error & the button is the "Log in" button & when I want to Sign in it also returned me the "Authentication failed" error. May I know what is the problem? May you help to rectify it? Thank you

**Comment by JohnHour89** [comment]
Hi Mr. DimitriMikadze,

You can close the case now, this is because the "Authentication failed" error is due to the my firebase.json didn't configure it up properly. Thank you

**Comment by JohnHour89** [comment]
Hi Mr. DimitriMikadze,

You can close the case now, this is because the "Authentication failed" error is due to the my firebase.json didn't configure it up properly. Thank you

**Comment by JohnHour89** [comment]
Hi Mr. DimitriMikadze,

You can close the case now, this is because the "Authentication failed" error is due to the my firebase.json didn't configure it up properly. Thank you

**Comment by JohnHour89** [comment]
Hi Mr. DimitriMikadze,

You can close the case now, this is because the "Authentication failed" error is due to the firebase.json I didn't configure it up properly. Thank you

**Comment by JohnHour89** [comment]
Hi Mr. DimitriMikadze,

You can close the case now, this is because the "Authentication failed" error is due to the firebase.json I didn't configure it up properly. Thank you

**Comment by DimiMikadze** [comment]
JohnHour89 Great, glad you resolved the issue!
