### ISSUE TITLE
scene_1_post conflicts withanother child

### ISSUE THREAD

**Issue by codejoe** [DimitriMikadze/firebase-react-native-redux-starter#9]
Hi Dimitry

I found your demo app very useful, but I got an error when I have 3 users in firebase. This error "scene_1_post conflicts withanother child" appear when I want to login with another user. Anyone had experienced with this error?

Thanks

**Comment by DimiMikadze** [comment]
Hi @codejoe thanks, unfortunately i have no idea what's that error is about, i believe it's something related with firebase configuration?

**Comment by codejoe** [comment]
i am using same config in the documentation,
/src/firebase.json
{
  "apiKey": "xxx",
  "authDomain": "xxx",
  "databaseURL": "xxx",
  "storageBucket": "xxx",
  "messagingSenderId": "xxx"
}

and firebase rules:
{
  "rules": {
    "users": {
      "$uid": {
        ".read": "$uid === auth.uid",
        ".write": "$uid === auth.uid"
      }
    }
  }
}

yea maybe it's related with firebase auth

**Comment by DimiMikadze** [comment]
@codejoe hi, did you managed to resolve your issue?

**Comment by clickglue** [comment]
This might help?
https://github.com/aksonov/react-native-router-flux/issues/1144
